# walrus.yml

# set the system user that walrus will use to launch the craftbukkit
# server and send commands
walrus_user: "komidore64"

# permanent download link to get the latest craftbukkit jar
craftbukkit_dl_link: 'http://dl.bukkit.org/downloads/craftbukkit/get/latest-rb/craftbukkit.jar'

# should walrus automatically update the craftbukkit jar?
autoupdate_jar: true

# should walrus automatically create backups of the world?
autobackup: true

# how much memory should craftbukkit have allocated to it when the
# server is started (in megabytes)
#
# recommended minimum is atleast 1024 megabytes
craftbukkit_minimum_memory: 1024

# the maximum amount of memory that the craftbukkit server is
# allowed to use (in megabytes)
#
# should be set above starting memory
#
# recommended: 2048 megabytes
craftbukkit_maximum_memory: 2048

# a temporary location where overviewer copies the minecraft
# world so that it can parse and render the world. if the
# directory does not exist, it will be created, and then
# deleted upon successful render
overviewer_temporary_dir: '/tmp/overviewer'

# overviewer's output directory is where the web files
# will be placed once the minecraft world parsing is
# done
overviewer_output_dir: '/var/www/html'
